language: ruby
before_install:
 - cp config/kippt.yml.example config/kippt.yml
bundler_args: --without development
script:
  - bundle exec rake db:create
  - bundle exec rake db:schema:load
  - bundle exec rspec
rvm:
  - 2.0.0
branches:
  only:
    - master
    - production
notifications:
  email:
    - london@railsgirls.co.uk
